apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: "openstack"
    octavia.ingress.kubernetes.io/internal: "false"
    octavia.ingress.kubernetes.io/backend-protocol: "HTTP"
    octavia.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.path }}
        pathType: Exact
        backend:
          service:
            name: {{ .Values.container.name }}-service
            port:
              number: {{ .Values.container.port }}
