apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-for-nginx
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.container.name }}-service
            port:
              number: {{ .Values.container.port }}
